### ISSUE TITLE
Prepare distribution

### ISSUE THREAD

**Issue by ForNeVeR** [ForNeVeR/bloodmasters#11]
Prepare the game distribution (client + launcher, server) for each build.

**TODO**
- [x] Dev mode build
  - [x] Make Client work from default bin dir
  - [x] Make Launcher work from default bin dir
  - [x] Make DedicatedServer work from default bin dir
- [x] Extract `Build/*` into a separate `Content` project
  - [x] On build, do nothing
  - [x] On `pack`, use a local RAR archiver
    - Or even one we will write?
- [ ] Ideally, `dotnet publish` should prepare a full game distribution
- [ ] Upload those packs to GitHub Actions
- [ ] Document how to get the latest version of the game
