### ISSUE TITLE
Startup error about DirectX DLL

### ISSUE THREAD

**Issue by ForNeVeR** [ForNeVeR/bloodmasters#29]
privately reported problem:
![image_2023-07-10_19-50-24](https://github.com/ForNeVeR/bloodmasters/assets/92793/653f08b6-25e4-45be-8650-2f9f19513e29)

Probably we need DirectX 9 installed on the user's computer, or something like that?

## TODO
- [ ] Bundle the libraries for use in dev mode
  - [ ] If impossible to bundle, figure out how to install, and add the information into the contributor guide
- [ ] Make sure the libraries are also available in the installed version of the game
  - [ ] Either open a new task for installer, or make sure they get bundled by either `dotnet build` or `dotnet pack` properly
- [ ] If we figure out anything new, add our information to [this old question on Stack Overflow](https://stackoverflow.com/q/27096103/2684760)

**Comment by KeterSCP** [comment]
So based on https://stackoverflow.com/a/28500257, I've prepared a minimal required DirectX redist:

[dx_redist.zip](https://github.com/ForNeVeR/bloodmasters/files/12207174/dx_redist.zip)

**Comment by ForNeVeR** [comment]
Gosh this is complicated.

Okay, the current plan then will be:
- [ ] Create a separate GitHub project 
  - This will be a messy activity, but 
- [ ] Push a script that will get these files from their origin, verify the hashes and pack them
  - _Why so complicated?_ Because nobody should believe you, or me, or others in delivering the binaries, and thus the workflow of packing any artifact, even of this one-shot kind, should be fully automated and verifiable.
- [ ] Run the script and publish the files to NuGet.org
  - Why nuget? Because that's the best storage for binaries in .NET. Even if we aren't using them as direct assembly references.
- [ ] Download/reference the package on build
- [ ] Bundle it into the installer and run installation
- [ ] Add information about installation into the contributor guide

**Comment by ForNeVeR** [comment]
But then, have you taken a look at https://www.nuget.org/packages/Microsoft.DXSDK.D3DX? It seems to contain the libraries we need (at least `D3DX9_43.dll` is there), and the license seems to allow redistribution in the mode we want to.

Maybe let's start investigating that?

I've read [this old article](http://web.archive.org/web/20150214193556/http://blogs.msdn.com/b/chuckw/archive/2010/09/08/not-so-direct-setup.aspx) linked from the link you found, and it seems to indicate that DirectX is _mostly_ available on the modern systems, with a small exception of D3DX, whatever the hell is that.
