### ISSUE TITLE
Fix namespaces in the code

### ISSUE THREAD

**Issue by ForNeVeR** [ForNeVeR/bloodmasters#44]
Currently, most of our code lives in `CodeImp.Bloodmasters`, but certain parts are in just `Bloodmasters`.

Also, not all the namespaces correspond to the file layout.

Let's fix all this.

### TODO
- [x] #10
- [x] Fix most namespaces
- [ ] Fix the namespaces in Launcher
- [ ] Make sure there are no folders that are _not_ namespace providers left
